# Generated by Django 3.0.5 on 2020-04-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200427_2239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'permissions': (('can_modify_author', 'Add, Modify and Delete author'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': (('can_modify_book', 'Add, Modify and Delete book'),)},
        ),
    ]
